name: Testing Workflow # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - main
    paths:
     - '.github/workflows/**'

# Job called build runs-on ubuntu-latest
jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    # Checkout to the repository
    - uses: actions/checkout@v3

    # We need to login so we can later push the image without issues.
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Builds 
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: vishnuve/devops_for_docker:express